---
# ExternalName service redirects Prowlarr's FlareSolverr requests
# to the VPN-protected instance in the downloads namespace
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  namespace: media
  labels:
    app: flaresolverr
spec:
  type: ExternalName
  externalName: flaresolverr.downloads.svc.cluster.local
