---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sabnzbd-server-config
  namespace: downloads
data:
  servers.ini: |
    [servers]
    [[newshosting]]
    name = newshosting
    displayname = Newshosting
    host = news.newshosting.com
    port = 563
    timeout = 60
    username = ${NEWSHOSTING_USER}
    password = ${NEWSHOSTING_PASS}
    connections = 30
    ssl = 1
    ssl_verify = 2
    ssl_ciphers = ""
    enable = 1
    required = 0
    optional = 0
    retention = 0
    send_group = 0
    priority = 0
    notes = ""
