---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storage/local-path
  - monitoring
  - security
  - backup
  # - image-automation  # Requires: flux install --components-extra=image-reflector-controller,image-automation-controller
