---
apiVersion: v1
kind: ConfigMap
metadata:
  name: crowdsec-acquis
  namespace: security
data:
  # Read Traefik access logs from container log files on the node
  traefik.yaml: |
    filenames:
      - /var/log/containers/traefik-*_traefik_traefik-*.log
    labels:
      type: traefik
