---
apiVersion: v1
kind: Service
metadata:
  name: maintainerr
  namespace: media
  labels:
    app: maintainerr
spec:
  type: ClusterIP
  ports:
    - port: 6246
      targetPort: 6246
      protocol: TCP
      name: web
  selector:
    app: maintainerr
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: maintainerr
  namespace: media
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: maintainerr.brzrkr.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: maintainerr
                port:
                  number: 6246
